name: MultiHome
main: com.plug.multihome.MultiHomePlugin
version: 1.0.1
authors:
  - domsonhere
api-version: 1.20
commands:
  sethome:
    description: Ustawia dom o podanej nazwie
    usage: /sethome <nazwa>
    aliases: [mhset]
  home:
    description: Teleportuje do ustawionego domu
    usage: /home <nazwa>
    aliases: [mh]
  delhome:
    description: Usuwa ustawiony dom
    usage: /delhome <nazwa>
    aliases: [mhd]
permissions:
  multihome.use:
    description: Pozwala korzystać z komend sethome i home
    default: true
